### ISSUE TITLE
CC2652 or CC2538 + CC2592 instead of CC2530 + CC2592 combo?

### ISSUE THREAD

**Issue by Gamester17** [electrolama/zoe#1]
@omerk have you considered using CC2538 instead of CC2530 on your zoe board?

CC2538 is more powerful and has more RAM so is capable of running Z-Stack 3.x for Zigbee 3.0

As a bonus, you could then run same version of Z-Stack 3 on zoe and zig-a-zig-ah!

See:
- https://github.com/Koenkk/zigbee2mqtt/issues/1568 

and:
- https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator

**Comment by omerk** [comment]
Hey @Gamester17,

Similar discussion here: https://github.com/electrolama/zig-a-zig-ah/issues/4

I already have a mock-up of "zoe2" (better name suggestion?) and I will publish that once I am done with the current zoe and zzh revisions. CC2652 is the way to go, skipping CC2538.

Keep an eye on https://electrolama.com or [Subscribe to the mailing list](https://mailchi.mp/1746be86dd81/electrolama) to get updates when I publish more projects.
