### ISSUE TITLE
[REQUEST] Add an antenna port on the zoe board for connecting external antenna to reduce interference and improve signal reception?

### ISSUE THREAD

**Issue by Hedda** [electrolama/zoe#2]
@omerk Have you considered adding an antenna port for connecting an external antenna to the zoe?

Not sure if a standard SMA (female) port would be a good choice on a HAT board as then not all Raspberry Pi enclosures would work without modification to the case, so can I suggest that you consider using a surface mounted Hirose U.FL a.k.a. "uFL" (female) port on the zoe board as they are already common on WiFi-adapters that have a Mini-PCIe/Mini-PCI/M.2 form-factor so there are plenty of inexpensive external 2.4GHz antennas an antenna-converters available for uFL ports? 

https://en.wikipedia.org/wiki/Hirose_U.FL

The downside to the uFL (female) port is then one probably always has to uFL-female to SMA-female adapter in order to use an antenna with a SMA-male connection which is standard. 

https://en.wikipedia.org/wiki/Hirose_U.FL#/media/File:2_mm_SMD_UFL_Socket.jpg

Bonus with an external antenna is that the Raspberry Pi internal WiFi should in theory not interfere as much the signals to and from the zoe HAT as if it would if it use an integrated antenna.

**Comment by Hedda** [comment]
@omerk any feedback on uFL-port suggestion to simplify support for adding an external-antenna?

**Comment by omerk** [comment]
Hey @Hedda, great suggestion!

The radio module I use on zoe comes in two flavours:

E18-MS1PA1-PCB:

![image](https://user-images.githubusercontent.com/9847/77589908-77385200-6ee4-11ea-80ed-13b73a40d2b7.png)

and E18-MS1PA1-IPX:

![image](https://user-images.githubusercontent.com/9847/77589877-67b90900-6ee4-11ea-88af-f5c820b698b6.png)

Good news is that they are footprint compatible, -IPX is a little shorter than -PCB but that's only a minor cosmetic issue, so if you wanted to use an external antenna you could very easily do that without any design changes.

Moving the antenna away is theoretically a good move but I would still strongly suggest that you disable the WiFi and Bluetooth on the Pi as you will not be able to get far enough from it to make any real difference in terms of RF interference. Also, as you have pointed out, finding a case to fit it all also becomes an issue.

The ideal and intended use case for zoe is a Pi with wired Ethernet, it sits somewhere where you can pull an Ethernet cable to (and even use PoE to power it all if you don't want to deal with pulling power separately as well!) and the only radio working is the E18 module.

**Comment by Hedda** [comment]
@omerk OK but that would make the external-antenna mandatory. 

I was thinking that it would maybe be best with a design somehow and change the zoe board so that external-antenna could be made optional on the same board using the same radio module, however for that I guess it would need both integrated circuit board antenna as well as a uFL-port.

Ideas?

Perhaps as a  quick-and-dirty design-change workaround could be to use E18-MS1PA1-IPX but then also add a male uFL-port as well a integrated circuit board antenna to the zoe board and have a short male to female uFL antenna cable go-between the E18-MS1PA1-IPX radio module and the zoe board if you want to use the integrated circuit board antenna?

**Comment by omerk** [comment]
The PCB trace antenna and the CC2592 range extender does a very good job without the need of an external antenna in my opinion and experience. 

The key to a sensible Zigbee deployment is to have routers distributed around the house to form a good mesh network. Having the most powerful antenna on the coordinator is not going to magically fix all the range issues.

Given that there is already a workable solution in the form of an alternative module if you absolutely need an external antenna and the fact that the performance of the PCB antenna is satisfactory, I don't see the benefit of modifying the design.

Of course, this is an open-source hardware project and anyone is free to modify the design as they see fit. Keep in mind, the moment you add your own antenna on a PCB you then need to make sure it is matched and positioned correctly.
