### ISSUE TITLE
Programming mode

### ISSUE THREAD

**Issue by emc02** [electrolama/zoe#5]
Hello, is the device working in programming mode too? Or do I have to put the Switches back to normal Mode after programming?
I am asking because I am working on an big project and would need to flash unattended.
Thanks!

**Comment by omerk** [comment]
Hi @emc02, zoe design should be considered "retired" as it is based on older generation chips. zoe2, based on the newer CC1352P will be released soon, sign up to the [mailing list](https://electrolama.com/list) if you'd like to hear when it is released.

To answer your question, you will be able to program zoe2 "unattended" by bridging GPIO that controls the BSL trigger and RESET. I've also brought out the JTAG pins for OpenOCD but have not yet managed to get it working.
